### ISSUE TITLE
Call to a member function process() on null (since v5.1.0)

### ISSUE THREAD

**Issue by booooza** [Flowpack/Flowpack.ElasticSearch#103]
Release [5.1.0](https://github.com/Flowpack/Flowpack.ElasticSearch/releases/tag/5.1.0) seems to break things for us.

```

Call to a member function process() on null

  Type: Error
  File: Data/Temporary/Production/Cache/Code/Flow_Object_Classes/Flowpack_ElasticSe
        arch_Domain_Model_Index.php
  Line: 209
```

Seems DynamicIndexSettingService is not yet available during injectSettings()?

Non-breaking but IMHO the default value for CURLOPT_SSL_VERIFYHOST should be set to 2.  curl_setopt_array(): CURLOPT_SSL_VERIFYHOST no longer accepts the value 1, value 2 will be used instead (see https://www.php.net/manual/en/function.curl-setopt.php)

**Comment by DrillSergeant** [comment]
Same issue here with 5.1.1 when calling `./flow node:repair`

```
./flow node:repair
Run checks for basic node integrity in the content repository

Checking for nodes with abstract or undefined node types ...
Checking for orphan nodes ...
Checking for disallowed child nodes ...
Checking for undefined properties ...
Checking for broken entity references ...
Checking for nodes with invalid dimensions ...
Checking for nodes with invalid workspace ...
Checking for nodes with inconsistent identifier ...
Checking for missing child nodes ...
 ❱ Add node dad9deb8-f493-5f14-0cc6-34c8180b8480 named "autoshortcuts" in "/sites/internezzo-site"
    applied ✔
Created 1 new child nodes
Call to a member function process() on null

  Type: Error
  File: Data/Temporary/Development/SubContextDdev/Cache/Code/Flow_Object_Classes/Fl
        owpack_ElasticSearch_Domain_Model_Index.php
  Line: 209
```

**Comment by simonhir** [comment]
The commit that leads to the error seams to be b8a4f9ceee1d6ae2f44a9cf79262f68c008e5aa8.

In my opionen the problem is that when calling the `getSettings()` function the needed class `DynamicIndexSettingService` isn't injected yet.

**Comment by snoblucha** [comment]
@simonhir this is exactly the issue.  Because when Flow compiles it generates this method

```
    private function Flow_Proxy_injectProperties()
    {
        $this->injectSettings(\Neos\Flow\Core\Bootstrap::$staticObjectManager->get(\Neos\Flow\Configuration\ConfigurationManager::class)->getConfiguration('Settings', 'Flowpack.ElasticSearch'));
        $this->Flow_Proxy_LazyPropertyInjection('Flowpack\ElasticSearch\Service\DynamicIndexSettingService', 'Flowpack\ElasticSearch\Service\DynamicIndexSettingService', 'dynamicIndexSettingService', 'a084c9e1cc42f5f542a97a68fba74866', function() { return \Neos\Flow\Core\Bootstrap::$staticObjectManager->get('Flowpack\ElasticSearch\Service\DynamicIndexSettingService'); });
        $this->Flow_Injected_Properties = array (
  0 => 'settings',
  1 => 'dynamicIndexSettingService',
);
    }
```

and when 

`$this->injectSettings` is called the $this->Flow_Proxy_LazyPropertyInjection is not called yet, thus `$this->dynamicIndexSettingService` is null at the moment in  `protected function getSettings()`

**Comment by DrillSergeant** [comment]
I wonder why there is not a lot of traffic about this ticket, we are hidden quite hard by this issue, every Neos and Flow installation who did a composer update in the last 2 weeks was broker afterwards, sometimes not easy to spot the problem. I assumed everybody to be affected by this bug, but maybe I am mistaken.

Anyway, if there is someone to fix it, I would appreciate and I can offer some budget for it.

**Comment by rolandschuetz** [comment]
The problem is that injectSettings calls [getSettings() here](https://github.com/Flowpack/Flowpack.ElasticSearch/pull/88/files#diff-513b5e9891f470b019f887a15f11fe078f56c454a320cc3afcfe27d927c4c1d1R125).
