### ISSUE TITLE
realtimeIndexing.enabled should be taken from TYPO3CR.Search settings

### ISSUE THREAD

**Issue by kdambekalns** [Flowpack/Flowpack.ElasticSearch#19]
Right now there is Flowpack.ElasticSearch.realtimeIndexing.enabled but the same setting is also present in the TYPO3.TYPO3CR.Search settings. To avoid confusion, the setting from TYPO3CR.Search should be used.

**Comment by flrnmllr** [comment]
I want to use Flowpack.ElasticSearch in a Flow application without Neos. Now I have to set the Setting TYPO3.TYPO3CR.Search.realtimeIndexing.enabled in my application for a Package, I do not have installed. Wouldn't it be more logical, to use the Setting Flowpack.ElasticSearch.realtimeIndexing.enabled in TYPO3.TYPO3CR.Search?

**Comment by kdambekalns** [comment]
This has been solved, but has become another issue… #29
