### ISSUE TITLE
Indexing huge amounts of objectes eats up huge amount of memory

### ISSUE THREAD

**Issue by thomasblass** [Flowpack/Flowpack.ElasticSearch#33]
If you Index huge amounts ob objects, the indexer eats up more and more memory. I tracked it down to ObjectIndexer.indexObject.
The ObjectIndexer tracks the objects which are already indexed in handledObjects, which increases dramatically when indexing several 100.000 of objects.

**Comment by dfeyer** [comment]
We also have this problem. I can send a small PR to fix this

If you have really big index and can use an job queue server, you can try https://github.com/ttreeagency/Flowpack.ElasticSearch.ContentRepositoryQueueIndexer, who use a async jobs to handle the ES indexing, speed thing a lots (can do thinks in paralel) and use less memory

**Comment by dfeyer** [comment]
@thomasblass can you test #34 ?

**Comment by dfeyer** [comment]
Hi the PR #34 is now merged, try to use the master version of this package should solve your issue, if not reopen to issue, thanks
