### ISSUE TITLE
Indexing not possible when peer cannot be verified

### ISSUE THREAD

**Issue by frozenstupidity** [Flowpack/Flowpack.ElasticSearch#97]
Unfortunately it is not possible to index the nodes if the ElasticSearch instance is running on a self signed certificate and only accessible via https.

This is due to the inability to configure the curl option for ssl verification.

**Comment by frozenstupidity** [comment]
I have updated this with a pull request https://github.com/Flowpack/Flowpack.ElasticSearch/pull/98 I hope this helps, let me know if you have any questions.

**Comment by kitsunet** [comment]
Seems this was solved?
